### Lecture Day-7
## Numpy

In [3]:
# creating basic array
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [7]:
c= np.ones(6)
c

array([1., 1., 1., 1., 1., 1.])

In [9]:
# create an empty array
d = np.empty(4)
d

array([2.12199579e-314, 8.31822350e-312, 4.80231808e-321, 3.79442416e-321])

In [10]:
# array with range
h = np.arange(6)
h

array([0, 1, 2, 3, 4, 5])

In [11]:
# array with even distribution
g = np.arange(2,9,2)
g

array([2, 4, 6, 8])

## Adding or Removing and elements

In [13]:
arr = np.array([2,6,2,5,2,5,4,85])
np.sort(arr)

array([ 2,  2,  2,  4,  5,  5,  6, 85])

In [14]:
# concatenate
n = np.array([1,2,5,3,8,5])
j = np.array([5,5,3,6,5,4,7])
np.concatenate((n,j))

array([1, 2, 5, 3, 8, 5, 5, 5, 3, 6, 5, 4, 7])

## Basic array operations

In [15]:
data = np.array([7, 2])
ones = np.ones(2, dtype=int)
data + ones

array([8, 3])

## Broadcasting

In [17]:
data = np.array([4.0, 2.0])
data * 2

array([8., 4.])

## Creating matrices

In [19]:
arr = np.array([[1, 3], [4, 4], [5, 9]])
arr

array([[1, 3],
       [4, 4],
       [5, 9]])

In [21]:
#selecting element at (row 0 and col 2)
arr[0,1]

3

In [23]:
#selecting element from rown 1,3
arr[1:3]

array([[4, 4],
       [5, 9]])

In [24]:
#selecting elements from row 0-2 at column 0
arr[0:2,0]

array([1, 4])

In [25]:
#selecting element from 0-1 at column 1
arr[0:1,1]

array([3])